feat: Pricing
pluralsh/console pull request #312
Opened 2023-03-06 09:44 UTC by maciaszczykm

## Summary

## Test Plan

## Checklist
- [ ] If required, I have updated the Plural documentation accordingly.
- [ ] I have added tests to cover my changes.
- [ ] I have added a meaningful title and summary to convey the impact of this PR to a user.
- [ ] I have added relevant labels to this PR to help with categorization for release notes.

2023-03-08 17:17 UTC, dogmar requested changes
Looks good. Just a few little text changes.

2023-03-09 07:50 UTC, maciaszczykm commented on assets/src/components/billing/BillingFeatureBlockBanner.tsx
> +  if ((account?.availableFeatures || {})[planFeature] || isPaidPlan) return null
Yes, it will look cleaner. Thanks!

2023-03-09 13:49 UTC, floreks approved these changes

2023-03-09 18:32 UTC, dogmar approved these changes

2023-03-10 08:24 UTC, merged